// =========================================================================
// MODULE 3 - EXPORT SENTINEL-1 AND SAOCOM COMPOSITES
// =========================================================================


// OBJECTIVE: Materialise the  Sentinel-1 and SAOCOM composites generated by Module 2 as permanent GEE assets.

// RUN IT IN GOOGLE EARTH ENGINE.

// -------------------------------------------------------------------------
// 1. LOAD PARAMETERS AND FINAL ROI-PREPARATION MODULE
// -------------------------------------------------------------------------
var params = require('users/SSoubie95/CASA25:Dissertation/0_data_load_and_parameter_settings');
var roi = require('users/SSoubie95/CASA25:Dissertation/2_roi_preparation');

// -------------------------------------------------------------------------
// 2. LOAD THE FINAL COMPOSITES
// -------------------------------------------------------------------------
var s1Composite = roi.s1Composite;
var saocomComposite = roi.saocomComposite;

// -------------------------------------------------------------------------
// 3. QUICK SANITY CHECK
// -------------------------------------------------------------------------
print(
  'Sentinel-1 composite bands:',
  s1Composite.bandNames()
);

print(
  'SAOCOM composite bands:',
  saocomComposite.bandNames()
);

// -------------------------------------------------------------------------
// 4. EXPORT SENTINEL-1 COMPOSITE
// -------------------------------------------------------------------------
Export.image.toAsset({
  image: s1Composite,
  description: 's1_composite_corrected',
  assetId: 'projects/divine-engine-488410-g2/assets/images/s1_composite_corrected',
  region: params.basinGeom,
  crs: params.WORKING_CRS,
  scale: 10,
  maxPixels: 1e13,
  pyramidingPolicy: { '.default': 'mean' }
});


// -------------------------------------------------------------------------
// 5. EXPORT SAOCOM COMPOSITE
// -------------------------------------------------------------------------
Export.image.toAsset({
  image: saocomComposite,
  description: 'saocom_composite_corrected',
  assetId: 'projects/divine-engine-488410-g2/assets/images/saocom_composite_corrected',
  region: params.basinGeom,
  crs: params.WORKING_CRS,
  scale: 10,
  maxPixels: 1e13,
  pyramidingPolicy: { '.default': 'mean' }
});